### ISSUE TITLE
Knapsack::Adapters::RSpecAdapter does not track time spent in `before` or `after` `:context`

### ISSUE THREAD

**Issue by caalberts** [KnapsackPro/knapsack#106]
Hi. In our project, we found that `Knapsack::Adapters::RSpecAdapter` does not track time spent in `before` or `after` `:context`.

Because of this, the distribution of the parallel job duration becomes uneven as the jobs that have the tests with longer set up time will take longer than the average. 

Is this intended?

**Comment by ArturT** [comment]
I recall a similar thing was already fixed in `knapsack_pro` ruby gem.

Related PRs:

* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/62
* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/52

You can learn how Knapsack Pro Queue Mode can help you save more time:
https://docs.knapsackpro.com/2020/how-to-speed-up-ruby-and-javascript-tests-with-ci-parallelisation

If you like to improve `knapsack` gem you can prepare PR with a fix. You can use this project for debugging purpose in development https://github.com/KnapsackPro/rails-app-with-knapsack
and this script to run RSpec tests  https://github.com/KnapsackPro/rails-app-with-knapsack/blob/master/bin/knapsack_rspec

**Comment by caalberts** [comment]
Thanks for clarifying @ArturT. We have done a patch in https://gitlab.com/gitlab-org/gitlab/-/merge_requests/58980.

I'll port it over into a PR for you to review.

**Comment by caalberts** [comment]
I realized I wasn't very clear in the title and earlier comment that this is referring to `before(:context)` and `after(:context)`.
