### ISSUE TITLE
Ignore some test

### ISSUE THREAD

**Issue by eddbrown** [KnapsackPro/knapsack#73]
Hey there!

You can selectively run some tests by specifying their directory, but is there a way to deselect some tests and keep the others?

Thanks!

**Comment by ArturT** [comment]
You can pass arguments to test runner the same way as you do it right now by using just test runner alone.

https://github.com/ArturT/knapsack#passing-arguments-to-rake-task

For instance, you can use RSpec tags and tell the RSpec to skip some of them:

```
bundle exec rake "knapsack:rspec[--tag ~skipTagName]"
```

What problem do you want to solve?

--- 
NOTE: this issue is related to https://github.com/KnapsackPro/knapsack_pro-ruby/issues/57

**Comment by egze** [comment]
I have a similar feature request.

My use case is this. We have the following structure:
```
spec
├── acceptance
├── controllers
├── decorators
├── features
```
Acceptance folder has capybara specs with Chrome and requires a certain setup and is run in a separate pipeline and docker container. All the other specs are splitted with knapsack and run in parallel.

We want to exclude `acceptance` folder completely, but can't do it with just a `KNAPSACK_TEST_FILE_PATTERN` because internally knapsack does `Dir.glob` and there is no good way to exclude stuff. What also doesn't work is passing `--exclude-pattern` argument to `knapsack:rspec["--exclude-pattern 'acceptance'"]`.

What would be nice is a `KNAPSACK_TEST_FILE_EXLUDE_PATTERN` that is used after `Dir.glob`.

**Comment by ArturT** [comment]
The exclude pattern is now available in Knapsack Pro version:
https://github.com/KnapsackPro/knapsack_pro-ruby#how-to-exclude-tests-from-running-them

**Comment by robertwe** [comment]
@ArturT what with the support for path exclusion in free version of the Knapsack?

**Comment by ArturT** [comment]
Hi @robertwe 

We are focused on improving the knapsack_pro gem. Support from our users is the way to ensure we provide maintenance of the project in the long run. knapsack_pro gem offers superior functionality, here are some examples for excluding patterns:

* https://knapsackpro.com/faq/question/how-to-exclude-tests-from-running-them
* https://knapsackpro.com/faq/question/dir-glob-pattern-examples-for-knapsack_pro_test_file_pattern-and-knapsack_pro_test_file_exclude_pattern
* https://knapsackpro.com/faq/question/how-to-run-only-a-specific-set-of-test-files-in-rspec
* https://knapsackpro.com/faq/question/how-to-run-a-specific-list-of-test-files-or-only-some-tests-from-test-file 

There is also [a free plan for knapsack_pro gem](https://knapsackpro.com/?utm_source=github&utm_medium=github-issue&utm_campaign=knapsack_gem_github_issue_73) if you'd like to try it.

**Comment by qileilove** [comment]
is anything updated on this topic?

**Comment by ArturT** [comment]
@qileilove Could you share more about your project and what kind of tests you need to ignore? Feel free to email me at support https://knapsackpro.com/contact if you don't want to share it publicly.

**Comment by 3v0k4** [comment]
We officially archived Knapsack, you can read more about it [here](https://knapsackpro.com/knapsack_gem).

Thank you for caring and creating this issue.

I'm sorry we couldn't get this done for you.
